### ISSUE TITLE
Corrupted Database

### ISSUE THREAD

**Issue by maximusVII** [eglia/ff-oc-passwords#27] opened 2016-10-19 09:43 UTC
After the modification of a password, I get the following add-on error message:

![capture](https://cloud.githubusercontent.com/assets/22932853/19513654/f351574a-95f0-11e6-92d1-233c526250a2.JPG)

I deleted already all passwords (0 entries in passwords app in owncloud) but the add-on in firefox is still telling me that there is one entry in the db and throwing the error message. There are no entries in the owncloud passwords db as well.

The error message seems to be strange as I'm not logged-in with the admin but an external user (xy@xy.com).

Thanks a lot for your help!

**Comment by moretocome** [comment] 2016-10-19 13:49
#26 
Same issue as me.

**Comment by ghost** [comment] 2016-10-20 13:58
This fixed in my latest master (Passwords app).

**Comment by eglia** [comment] 2016-10-21 18:03
duplicate of #26

**Closed as completed by eglia** 2016-10-21 18:03 UTC
