### ISSUE TITLE
After owncloud password change, addon does not work anymore

### ISSUE THREAD

**Issue by tapir** [eglia/ff-oc-passwords#20] opened 2016-09-01 12:42 UTC
I've changed my ownCloud server password.
Then I changed the password on the addon settings to the new one but the connection to server keeps timing out.
Tried cleaning the cache, removing/reinstalling the addon etc.

**Comment by eglia** [comment] 2016-10-08 08:59
Duplicate of #23

**Closed as completed by eglia** 2016-10-08 08:59 UTC
